
spring:
  application:
    name: user-service
  datasource:
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
        username: test@localhost
        password: test
      initialSize: 5
      minIdle: 1
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL spring.datasource.testWhileIdle=true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
server:
  port: 1112



mybatis-plus:
  mapper-location: classpath:mapper/*Mapper.xml

