spring:
  application:
    name: eureka-server

server:
  port: 1111

eureka:
  instance:
    hostname: peer1
  client:
    #不向注册中心注册自己
#    register-with-eureka: false
    #向注册中心注册自己
    register-with-eureka: true
    #不需要检索服务
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:1110/eureka/
  #关闭保护机制
  server:
    enable-self-preservation: false

